// GENERATED - DO NOT EDIT
// Generated by zfa for: Role
import 'package:zuraffa/zuraffa.dart' hide Role;

import '../../entities/role/role.dart';
import '../../repositories/role_repository.dart';

class CreateRoleUseCase extends UseCase<Role, Role> {
  CreateRoleUseCase(this._repository);

  final RoleRepository _repository;

  @override
  Future<Role> execute(Role params, CancelToken? cancelToken) async {
    cancelToken?.throwIfCancelled();
    return _repository.create(params);
  }
}

// END GENERATED
