name: zuraffa_permissions_android
description: The Android implementation of zuraffa_permissions (ActivityCompat-based).
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

flutter:
  plugin:
    implements: zuraffa_permissions
    platforms:
      android:
        package: com.zuraffa.permissions
        pluginClass: ZuraffaPermissionsPlugin
        dartPluginClass: ZuraffaPermissionsAndroid

dependencies:
  flutter:
    sdk: flutter
  zuraffa_permissions:
    path: ../
  zuraffa_permissions_platform_interface:
    path: ../zuraffa_permissions_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
