// GENERATED - DO NOT EDIT
// Generated by zfa for: UserPermission
import 'package:zuraffa/zuraffa.dart';

import '../../entities/user_permission/user_permission.dart';
import '../../repositories/user_permission_repository.dart';

class GrantPermissionToUserUseCase
    extends UseCase<UserPermission, UserPermission> {
  GrantPermissionToUserUseCase(this._repository);

  final UserPermissionRepository _repository;

  @override
  Future<UserPermission> execute(
    UserPermission params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.create(params);
  }
}

// END GENERATED
