// GENERATED - DO NOT EDIT
// Generated by zfa for: Permission
// zfa make Permission --methods=get,getList,create --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/permission/permission.dart';
import '../../domain/repositories/permission_repository.dart';
import '../datasources/permission/permission_datasource.dart';

class DataPermissionRepository
    with Loggable, FailureHandler
    implements PermissionRepository {
  DataPermissionRepository(this._dataSource);

  final PermissionDataSource _dataSource;

  @override
  Future<Permission> get(QueryParams<Permission> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<Permission>> getList(ListQueryParams<Permission> params) {
    return _dataSource.getList(params);
  }

  @override
  Future<Permission> create(Permission permission) {
    return _dataSource.create(permission);
  }
}

// END GENERATED
