// GENERATED - DO NOT EDIT
// Generated by zfa for: RolePermission
// zfa make RolePermission --methods=get,getList,create,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/role_permission/role_permission.dart';
import '../../domain/repositories/role_permission_repository.dart';
import '../datasources/role_permission/role_permission_datasource.dart';

class DataRolePermissionRepository
    with Loggable, FailureHandler
    implements RolePermissionRepository {
  DataRolePermissionRepository(this._dataSource);

  final RolePermissionDataSource _dataSource;

  @override
  Future<RolePermission> get(QueryParams<RolePermission> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<RolePermission>> getList(ListQueryParams<RolePermission> params) {
    return _dataSource.getList(params);
  }

  @override
  Future<RolePermission> create(RolePermission rolePermission) {
    return _dataSource.create(rolePermission);
  }

  @override
  Future<void> delete(QueryParams<RolePermission> params) {
    return _dataSource.delete(params);
  }
}

// END GENERATED
