// GENERATED - DO NOT EDIT
// Generated by zfa for: Role
// zfa make Role --methods=get,getList,create --repository
import 'package:zuraffa/zuraffa.dart' hide Role;

import '../../domain/entities/role/role.dart';
import '../../domain/repositories/role_repository.dart';
import '../datasources/role/role_datasource.dart';

class DataRoleRepository
    with Loggable, FailureHandler
    implements RoleRepository {
  DataRoleRepository(this._dataSource);

  final RoleDataSource _dataSource;

  @override
  Future<Role> get(QueryParams<Role> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<Role>> getList(ListQueryParams<Role> params) {
    return _dataSource.getList(params);
  }

  @override
  Future<Role> create(Role role) {
    return _dataSource.create(role);
  }
}

// END GENERATED
