// GENERATED - DO NOT EDIT
// Generated by zfa for: UserRole
// zfa make UserRole --methods=get,getList,create,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/user_role/user_role.dart';
import '../../domain/repositories/user_role_repository.dart';
import '../datasources/user_role/user_role_datasource.dart';

class DataUserRoleRepository
    with Loggable, FailureHandler
    implements UserRoleRepository {
  DataUserRoleRepository(this._dataSource);

  final UserRoleDataSource _dataSource;

  @override
  Future<UserRole> get(QueryParams<UserRole> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<UserRole>> getList(ListQueryParams<UserRole> params) {
    return _dataSource.getList(params);
  }

  @override
  Future<UserRole> create(UserRole userRole) {
    return _dataSource.create(userRole);
  }

  @override
  Future<void> delete(QueryParams<UserRole> params) {
    return _dataSource.delete(params);
  }
}

// END GENERATED
