// GENERATED - DO NOT EDIT
// Generated by zfa for: UserPermission
// zfa make UserPermission --methods=get,getList,create,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/user_permission/user_permission.dart';
import '../../domain/repositories/user_permission_repository.dart';
import '../datasources/user_permission/user_permission_datasource.dart';

class DataUserPermissionRepository
    with Loggable, FailureHandler
    implements UserPermissionRepository {
  DataUserPermissionRepository(this._dataSource);

  final UserPermissionDataSource _dataSource;

  @override
  Future<UserPermission> get(QueryParams<UserPermission> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<UserPermission>> getList(ListQueryParams<UserPermission> params) {
    return _dataSource.getList(params);
  }

  @override
  Future<UserPermission> create(UserPermission userPermission) {
    return _dataSource.create(userPermission);
  }

  @override
  Future<void> delete(QueryParams<UserPermission> params) {
    return _dataSource.delete(params);
  }
}

// END GENERATED
