// GENERATED - DO NOT EDIT
// Generated by zfa for: PermissionScope
// zfa make PermissionScope --methods=get,getList,create --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/permission_scope/permission_scope.dart';
import '../../domain/repositories/permission_scope_repository.dart';
import '../datasources/permission_scope/permission_scope_datasource.dart';

class DataPermissionScopeRepository
    with Loggable, FailureHandler
    implements PermissionScopeRepository {
  DataPermissionScopeRepository(this._dataSource);

  final PermissionScopeDataSource _dataSource;

  @override
  Future<PermissionScope> get(QueryParams<PermissionScope> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<PermissionScope>> getList(
    ListQueryParams<PermissionScope> params,
  ) {
    return _dataSource.getList(params);
  }

  @override
  Future<PermissionScope> create(PermissionScope permissionScope) {
    return _dataSource.create(permissionScope);
  }
}

// END GENERATED
