// GENERATED - DO NOT EDIT
// Generated by zfa for: PermissionScope
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/permission_scope/permission_scope.dart';
import '../../repositories/permission_scope_repository.dart';

class GetPermissionScopeUseCase
    extends UseCase<PermissionScope, QueryParams<PermissionScope>> {
  GetPermissionScopeUseCase(this._repository);

  final PermissionScopeRepository _repository;

  @override
  Future<PermissionScope> execute(
    QueryParams<PermissionScope> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
