// GENERATED - DO NOT EDIT
// Generated by zfa for: PermissionScope
// zfa make PermissionScope --methods=get,getList,create --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/permission_scope/permission_scope.dart';

abstract class PermissionScopeRepository {
  Future<PermissionScope> get(QueryParams<PermissionScope> params);
  Future<List<PermissionScope>> getList(
    ListQueryParams<PermissionScope> params,
  );
  Future<PermissionScope> create(PermissionScope permissionScope);
}

// END GENERATED
