// GENERATED - DO NOT EDIT
// Generated by zfa for: Permission
// zfa make Permission --methods=get,getList,create --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/permission/permission.dart';

abstract class PermissionRepository {
  Future<Permission> get(QueryParams<Permission> params);
  Future<List<Permission>> getList(ListQueryParams<Permission> params);
  Future<Permission> create(Permission permission);
}

// END GENERATED
