// GENERATED - DO NOT EDIT
// Generated by zfa for: RolePermission
// zfa make RolePermission --methods=get,getList,create,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/role_permission/role_permission.dart';

abstract class RolePermissionRepository {
  Future<RolePermission> get(QueryParams<RolePermission> params);
  Future<List<RolePermission>> getList(ListQueryParams<RolePermission> params);
  Future<RolePermission> create(RolePermission rolePermission);
  Future<void> delete(QueryParams<RolePermission> params);
}

// END GENERATED
