// GENERATED - DO NOT EDIT
// Generated by zfa for: Role
// zfa make Role --methods=get,getList,create --repository
import 'package:zuraffa/zuraffa.dart' hide Role;

import '../entities/role/role.dart';

abstract class RoleRepository {
  Future<Role> get(QueryParams<Role> params);
  Future<List<Role>> getList(ListQueryParams<Role> params);
  Future<Role> create(Role role);
}

// END GENERATED
