// GENERATED - DO NOT EDIT
// Generated by zfa for: UserRole
// zfa make UserRole --methods=get,getList,create,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/user_role/user_role.dart';

abstract class UserRoleRepository {
  Future<UserRole> get(QueryParams<UserRole> params);
  Future<List<UserRole>> getList(ListQueryParams<UserRole> params);
  Future<UserRole> create(UserRole userRole);
  Future<void> delete(QueryParams<UserRole> params);
}

// END GENERATED
