// GENERATED - DO NOT EDIT
// Generated by zfa for: UserPermission
// zfa make UserPermission --methods=get,getList,create,delete --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/user_permission/user_permission.dart';

abstract class UserPermissionRepository {
  Future<UserPermission> get(QueryParams<UserPermission> params);
  Future<List<UserPermission>> getList(ListQueryParams<UserPermission> params);
  Future<UserPermission> create(UserPermission userPermission);
  Future<void> delete(QueryParams<UserPermission> params);
}

// END GENERATED
