// GENERATED - DO NOT EDIT
// Generated by zfa for: Permission
import 'package:zuraffa/zuraffa.dart';

import '../../entities/permission/permission.dart';
import '../../repositories/permission_repository.dart';

class CreatePermissionUseCase extends UseCase<Permission, Permission> {
  CreatePermissionUseCase(this._repository);

  final PermissionRepository _repository;

  @override
  Future<Permission> execute(
    Permission params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.create(params);
  }
}

// END GENERATED
