// Auto-generated by Zorphy
// Generated at: 2026-08-23T18:59:41.024498

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'permission_scope.zorphy.dart';
part 'permission_scope.g.dart';

/// PermissionScope entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $PermissionScope {
  String get name;
  String get description;
  String get platformGroup;
  String get id;
}
