// GENERATED - DO NOT EDIT
// Generated by zfa for: PermissionScope
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/permission_scope/permission_scope.dart';
import '../../repositories/permission_scope_repository.dart';

class GetPermissionScopeListUseCase
    extends UseCase<List<PermissionScope>, ListQueryParams<PermissionScope>> {
  GetPermissionScopeListUseCase(this._repository);

  final PermissionScopeRepository _repository;

  @override
  Future<List<PermissionScope>> execute(
    ListQueryParams<PermissionScope> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.getList(params);
  }
}

// END GENERATED
