// GENERATED - DO NOT EDIT
// Generated by zfa for: RolePermission
import 'package:zuraffa/zuraffa.dart';

import '../../entities/role_permission/role_permission.dart';
import '../../repositories/role_permission_repository.dart';

class GrantPermissionToRoleUseCase
    extends UseCase<RolePermission, RolePermission> {
  GrantPermissionToRoleUseCase(this._repository);

  final RolePermissionRepository _repository;

  @override
  Future<RolePermission> execute(
    RolePermission params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.create(params);
  }
}

// END GENERATED
