// GENERATED - DO NOT EDIT
// Generated by zfa for: UserRole
import 'package:zuraffa/zuraffa.dart';

import '../../entities/user_role/user_role.dart';
import '../../repositories/user_role_repository.dart';

class AssignRoleToUserUseCase extends UseCase<UserRole, UserRole> {
  AssignRoleToUserUseCase(this._repository);

  final UserRoleRepository _repository;

  @override
  Future<UserRole> execute(UserRole params, CancelToken? cancelToken) async {
    cancelToken?.throwIfCancelled();
    return _repository.create(params);
  }
}

// END GENERATED
